### ISSUE TITLE
Jekyll Paginate V2

### ISSUE THREAD

**Issue by MihajloNesic** [lingxz/sparrow#7]
I know that there wasn't any updates to this theme in 2 years, but can we get a jekyll-paginate-v2 support?

Jekyll paginate v2 is an enhanced replacement for the old built-in jekyll-paginate. It supports pagination for collections. This is great because the Sparrow theme has pagination only for main blog (or only 1 collection).

[GitHub repo](https://github.com/sverrirs/jekyll-paginate-v2)

**Comment by lingxz** [comment]
upgraded to jekyll-paginate-v2 in 7997b3b.

**Comment by MihajloNesic** [comment]
Thank you very much. Is there a possibility you can add pagination support for collection/s ?

Edit: I actually managed to implement collection pagination. I'll fork the repo and do a pull request
